### ISSUE TITLE
Implement NextJS ISR for faster load times

### ISSUE THREAD

**Issue by Utkarshbhimte** [covidarmy/frontend#14]
Currently, the tweets are being fetched from the client. That can be fixed if we move the API calling to getStaticProps and use it as the default value on the state.

**Comment by nilshah98** [comment]
Hi @Utkarshbhimte good idea, but instead of SSG we could probably try ISR, which prevents whole thing from getting rebuilt, plus there are limits by vercel of upto 1000 deployment a day.

**Comment by arn4v** [comment]
@nilshah98 I believe Utkarsh was referring to ISR only. It's the approach we were already using but had issues with due to Twitter API calls. Now that we have a decoupled API we can reimplement ISR.

**Comment by nilshah98** [comment]
Oh, okay. My bad then.

**Comment by Utkarshbhimte** [comment]
How about we implement react-query to handle all our queries in the app?
https://react-query.tanstack.com/guides/ssr
