### ISSUE TITLE
Persist filters choices

### ISSUE THREAD

**Issue by Utkarshbhimte** [covidarmy/frontend#17]
We should persist filters, though we are redirecting to a page for every resource city combination usually, people would only remember the URL which is `covid.army`, if they see their filters reset then it would cause more anger and panic

**Comment by Utkarshbhimte** [comment]
@rgxai would love to know your thoughts on better visitor onboarding.

**Comment by rgxai** [comment]
Not sure if I understand this clearly. Can you explain better? I don't think the filters are being reset.

**Comment by jaisharx** [comment]
Redirections on homepage are usually a bad practice. It'll end up confusing more people than not. We already are persisting locations & resource state as url, so I don't think we need this.
