### ISSUE TITLE
Add powered by Vercel on the website

### ISSUE THREAD

**Issue by rgxai** [covidarmy/frontend#27]
We need to give credit to Vercel in order to get a sponsored account from them for being an open source project.

Instructions on what needs to be done can be found [here](https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project)

**Comment by bhatvikrant** [comment]
![powered-by-vercel](https://user-images.githubusercontent.com/50735025/117214368-55650a80-ae1a-11eb-8e0c-12d028d25e7e.png)
